### ISSUE TITLE
cli-platform-android ^4.5.1 fails to install app when ANDROID_HOME is not defined

### ISSUE THREAD

**Issue by es-lynn** [react-native-community/cli#1105]
## Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 64.61 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.1 - /Users/jaslyn/.rvm/gems/ruby-2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.0, 29.0.2
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_151 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

In react-native 0.61.5, `react-native run-android` runs without any problem.

react-native 0.61.5 uses cli-platform-android ^3.0.0

Expected result: 

```
Installed on 1 device.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 5s
209 actionable tasks: 3 executed, 206 up-to-date
info Connecting to the development server...
warn Failed to connect to development server using "adb reverse": spawnSync adb ENOENT
info Starting the app...
✨  Done in 9.58s.
```

______________

However In react-native 0.62.2, using cli-platform-android ^4.5.1,  `react-native run-android` throws 2 errors.

```
error Failed to launch emulator. Reason: No emulators found as an output of `emulator -list-avds`.
```

```
error Failed to start the app. Run CLI with --verbose flag for more details.
Error: spawnSync adb ENOENT
    at Object.spawnSync (internal/child_process.js:1041:20)
    at Object.spawnSync (child_process.js:609:24)
    at Function.module.exports.sync (/Users/me/Documents/company/git/project/project-mobile/node_modules/execa/index.js:334:30)
    at tryLaunchAppOnDevice (/Users/me/Documents/company/git/project/project-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/tryLaunchAppOnDevice.js:57:22)
    at /Users/me/Documents/company/git/project/project-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:104:39
    at Array.forEach (<anonymous>)
    at runOnAllDevices (/Users/me/Documents/company/git/project/project-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:102:48)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.handleAction (/Users/me/Documents/company/git/project/project-mobile/node_modules/@react-native-community/cli/build/index.js:186:9)
```
_______________

This can be fixed by injecting ANDROID_HOME path before running the script.

However given that this worked fine in ^3.0.0 without having to define ANDROID_HOME, but is only broken in ^4.5.1. Is this a bug or intentional behaviour?

## Reproducible Demo

1) Initialize a project on react-native 0.62.2
2) Ensure ANDROID_HOME environment variable is not set
3) Run react-native run-android

**Comment by thymikee** [comment]
We expect you to have `ANDROID_HOME` set. Can you run `adb` command from your default shell? Maybe you've updated Android SDK along the way and messed with adb paths?

**Comment by aiveneh** [comment]
similar issue here, I get
**` Failed to start the app`**

The app actually installs, but doesn't start up automatically as it did previously. I click on it to open and it works just fine.

**Comment by aelesia** [comment]
> We expect you to have `ANDROID_HOME` set. Can you run `adb` command from your default shell? Maybe you've updated Android SDK along the way and messed with adb paths?

Hi, no, my default shell was never configured to run adb. I usually run it from the directory itself.

It's still able to run 0.61.5 fine but not 0.62.2.
