### ISSUE TITLE
uninstall.test.ts fail on Windows CI

### ISSUE THREAD

**Issue by molant** [react-native-community/cli#1157]
While working on #1156 I've seen that e2e tests are failing on Windows. On CI they timeout while locally they fail in `uninstall.test.ts` and `uninstall module with npm` with a message that's confusing me:

```
 console.log jest/helpers.ts:194
      Running C:\Program Files\nodejs\node.exe command failed for unexpected reason. Here's more info:
      cmd:     C:\Program Files\nodejs\node.exe
      options: {"expectedFailure":false,"cwd":"C:\\Users\\antonmo\\AppData\\Local\\Temp\\command-uninstall-test"}
      args:    C:\projects\cli\packages\cli\build\bin.js uninstall react-native-config
      stderr:  warn Calling react-native unlink [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.
      Autolinking documentation: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
      warning package.json: No license field
      error No lockfile in this directory. Run `yarn install` to generate one.
      error Command failed: yarn remove react-native-config. Run CLI with --verbose flag for more details.

      stdout:  info Unlinking "react-native-config"...
      info Uninstalling "react-native-config"...
      info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.
      Error: Command failed: yarn remove react-native-config
          at makeError (C:\projects\cli\node_modules\execa\index.js:174:9)
          at C:\projects\cli\node_modules\execa\index.js:278:16
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
          at async Object.uninstall [as func] (C:\projects\cli\packages\cli\build\commands\install\uninstall.js:44:3)
          at async Command.handleAction (C:\projects\cli\packages\cli\build\index.js:186:9)
```

There are 2 things I don't understand:

> Calling react-native unlink [packageName] is deprecated in favor of autolinking. It will be removed in the next major release.

If this is no longer supported, can't we just remove this test?

Also the failing test is Uninstall module with **npm** but the output says:

> Command failed: yarn remove react-native-config

**Comment by thymikee** [comment]
We're removing install/uninstall in next major or so, I wouldn't bother too much
