### ISSUE TITLE
react-native doctor - Cannot destructure property 'contributor' of 'undefined' as it is undefined

### ISSUE THREAD

**Issue by shedali** [react-native-community/cli#1190]
## Environment

```System:
info Fetching system and libraries information...
(node:79226) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.62 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - ~/n/bin/node
    Yarn: 1.22.1 - ~/.config/yarn/global/node_modules/.bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

```

node:
~/n/bin/node v14.4.0 also node@12.18.0
npm 6.16.4/5
npx 6.14.5

## Description

npx @react-native-community/cli doctor --verbose

```error Cannot destructure property 'contributor' of 'undefined' as it is undefined.
TypeError: Cannot destructure property 'contributor' of 'undefined' as it is undefined.
    at getHealthchecks (/Users/franz/.npm/_npx/72902/lib/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:41:3)
    at Object._default [as func] (/Users/franz/.npm/_npx/72902/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:173:111)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.handleAction (/Users/franz/.npm/_npx/72902/lib/node_modules/@react-native-community/cli/build/index.js:184:9)
```

**Comment by haswalt** [comment]
---
name: 🐛 Report a bug
about: Report a reproducible or regression bug in React Native CLI.'
labels: 'bug report'
---

## Environment

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
    Memory: 10.44 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 26.0.1, 26.0.3, 27.0.3, 28.0.2, 28.0.3
      System Images: android-23 | Google APIs ARM EABI v7a, android-23 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_191 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

```
⠇ Running diagnostics...error Cannot destructure property `contributor` of 'undefined' or 'null'. Run CLI with --verbose flag for more details.
TypeError: Cannot destructure property `contributor` of 'undefined' or 'null'.
    at getHealthchecks (/Users/harry/.npm/_npx/6806/lib/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:40:26)
    at Object._default [as func] (/Users/harry/.npm/_npx/6806/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:173:111)
    at async Command.handleAction (/Users/harry/.npm/_npx/6806/lib/node_modules/@react-native-community/cli/build/index.js:184:9)
```


## Reproducible Demo

```
 npx @react-native-community/cli doctor
````

**Comment by mi-mazouz** [comment]
same issue after ejected expo app
