### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by mjfneto** [react-native-community/cli#1258]
## Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 5.91 GB / 15.89 GB
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\.yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.2
      System Images: android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6626763
    Visual Studio: Not Found
  Languages:
    Java: 1.8.0_211 - /c/Program Files/Java/jdk1.8.0_211/bin/javac
    Python: 2.7.18 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

## Description

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\####\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:968  throw err;  ^Error: Cannot find module 'C:\Users\####\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)    at Function.Module._load (internal/modules/cjs/loader.js:841:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

## Reproducible Demo

- Running Android Studio emulator online
- `yarn start` on one terminal
- `yarn android` on a second terminal

**Comment by mjfneto** [comment]
I had to fix the path to my project's files. Apparently gradle doesn't respond well if there are special characters or white space (my case) along the path. I think it's a closed case.
