### ISSUE TITLE
react-native link TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by phuongwd** [react-native-community/cli#1278]
## Environment

```
System:
    OS: macOS 11.0
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.7, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.2, 28.0.3, 29.0.1, 30.0.2
      System Images: android-21 | Intel x86 Atom, android-22 | ARM EABI v7a, android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom_64, android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom, android-R | Google APIs Intel x86 Atom_64, android-R | Google Play Intel x86 Atom, android-R | Google Play Intel x86 Atom_64
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 11.7/11E801a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Description

```
error The "path" argument must be of type string. Received type undefined. Run CLI with --verbose flag for more details.
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.basename (path.js:1289:5)
    at asset (/***/helloW/node_modules/@react-native-community/cli/build/commands/link/linkAll.js:56:87)
    at baseUniq (/***/helloW/node_modules/lodash/lodash.js:4296:35)
    at uniqBy (/***/helloW/node_modules/lodash/lodash.js:8440:40)
    at dedupeAssets (/***/helloW/node_modules/@react-native-community/cli/build/commands/link/linkAll.js:56:53)
    at linkAll (/***/helloW/node_modules/@react-native-community/cli/build/commands/link/linkAll.js:87:20)
    at Object.link [as func] (/***/helloW/node_modules/@react-native-community/cli/build/commands/link/link.js:80:33)
    at Command.handleAction (/***/helloW/node_modules/@react-native-community/cli/build/cliEntry.js:160:21)
    at Command.listener (/***/helloW/node_modules/commander/index.js:315:8)
```

## Reproducible Demo

- run `react-native link` on other project with react-native version 0.59
- success
- run `react-native link` on project with react-native version 0.60.5
- failed (error message as above)

https://github.com/facebook/react-native/issues/24103

**Comment by thymikee** [comment]
RN 0.60 is 3 versions behind the latest currently. We don't provide support for that, however we're ok with merging a fix to `2.x` branch of this repository, which corresponds to RN 0.60 release. 

Also, `link` is deprecated and going away soon, as we switched to [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md).
