### ISSUE TITLE
profile-hermes does not work on Windows

### ISSUE THREAD

**Issue by kidroca** [react-native-community/cli#1431]
## Environment

```sh
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 11.73 GB / 31.95 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31025.194 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: 4.13.1 => 4.13.1
    react: ^17.0.2 => 17.0.2
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

Running the following command (https://reactnative.dev/docs/next/profile-hermes#execute-command-from-cli)

```sh
npx react-native profile-hermes [destinationDir]
```

From a regular cmd terminal, or git bash or Powershell fails with an error: 

```sh
'egrep' is not recognized as an internal or external command,
operable program or batch file.

error Error: Command failed: adb shell run-as com.my-package.chat ls cache/ -tp | grep -v /$ | egrep '.cpuprofile' | head -1
```

##### Running with git bash
```sh
λ npx react-native profile-hermes ./ --verbose
info Downloading a Hermes Sampling Profiler from your Android device...
info No filename is provided, pulling latest file
'egrep' is not recognized as an internal or external command,
operable program or batch file.
error Error: Command failed: adb shell run-as com.my-package.chat ls cache/ -tp | grep -v /$ | egrep '.cpuprofile' | head -1

'egrep' is not recognized as an internal or external command,
operable program or batch file.

Error: Error: Command failed: adb shell run-as com.expensify.chat ls cache/ -tp | grep -v /$ | egrep '.cpuprofile' | head -1

'egrep' is not recognized as an internal or external command,
operable program or batch file.

    at getLatestFile (...\node_modules\react-native\node_modules\@react-native-community\cli-hermes\build\profileHermes\downl
oadProfile.js:92:11)
    at downloadProfile (...\node_modules\react-native\node_modules\@react-native-community\cli-hermes\build\profileHermes\dow
nloadProfile.js:117:30)
    at Object.profileHermes [as func] (...\node_modules\react-native\node_modules\@react-native-community\cli-hermes\build\pr
ofileHermes\index.js:28:48)
    at Command.handleAction (...\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:23)
    at Command.listener (...\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (...\node_modules\commander\index.js:651:12)
    at Command.parse (...\node_modules\commander\index.js:474:21)
    at setupAndRun (...\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:265:24)
    at Object.run (...\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:206:11)
```

A similar error happens using `PowerShell` or the standard `cmd` terminal 

```sh
'grep' is not recognized as an internal or external command,
operable program or batch file.
```

## Reproducible Demo

Run `npx react-native profile-hermes` on windows using a git bash terminal

**Comment by kidroca** [comment]
I'm not sure whether the pipes are intended to be handled by the `adb shell` or the parent terminal
The error happens because the parent terminal does not have some of the commands used
- git bash does not have `egrep` 
- while PowerShell and cmd don't have `grep` as well as `egrep` 

If the piping is intended to happen on the parent shell an easy fix might be to change `egrep` to `grep -E` as this will at least work in git bash: https://www.computerhope.com/unix/uegrep.htm
>  Running egrep is equivalent to running grep with the -E option.

**Comment by kidroca** [comment]
Indeed changing `egrep` to `grep -E` finishes successfully

```sh
λ npx react-native profile-hermes
info Downloading a Hermes Sampling Profiler from your Android device...
info No filename is provided, pulling latest file
info File to be pulled: sampling-profiler-trace8662843893976311132.cpuprofile
success Successfully converted to Chrome tracing format and pulled the file to D:\my-project/sampling-profiler-trace8662843893976311132-converted.json
```
