### ISSUE TITLE
[runIOS] --project-path flag not considered as Config

### ISSUE THREAD

**Issue by TheDuc** [react-native-community/cli#1437]
`warnAboutPodInstall` throws an error `error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?`

this is due to the fact that `--project-path` is set but not used to set the config files appropriately.
consider: https://github.com/react-native-community/cli/blob/641b21f583c97e3d48ce87d5fe804f42db92fa5c/packages/platform-ios/src/commands/runIOS/index.ts#L54

and:
https://github.com/react-native-community/cli/blob/641b21f583c97e3d48ce87d5fe804f42db92fa5c/packages/platform-ios/src/config/index.ts#L37

`projectConfig` tries to guess the location of the project files such as `Podfile.lock` but fails when there exists a directory that is **not** the correct project, but has a `.pbxproj` file in it but no Podfile as is the case in my case.

I have tried configuring the project files in `react-native.config` but failed to get it working. Also putting the projectPath in `react-native.config` would not be an ideal solution in my case, as the project location is dynamically generated (but supplied as `--project-path` flag to `run-ios`).

I know this is a quite specific issue, but any help would be greatly appreciated.

**Comment by TheDuc** [comment]
This issue is still present at the latest version (5.0.1) and the current next version (6.0.0).

However the error message has changed: 
```
error ENOENT: no such file or directory, open '/[REDACTED]/path/to/falsely/guessed/project/RNVAppTVOS.xcodeproj/project.pbxproj'.
Error: ENOENT: no such file or directory, open '/[REDACTED]/path/to/falsely/guessed/project/RNVAppTVOS.xcodeproj/project.pbxproj'
 at Object.openSync (fs.js:498:3)
 at Object.readFileSync (fs.js:394:35)
 at pbxProject.parseSync (/[REDACTED]/node_modules/xcode/lib/pbxProject.js:61:28)
 at isInstalled (/[REDACTED]/node_modules/react-native/node_modules/@react-native-community/cli-platform-ios/build/link/isInstalled.js:43:67)
 at Object.isInstalled (/[REDACTED]/node_modules/react-native/node_modules/@react-native-community/cli-platform-ios/build/link/common/isInstalled.js:23:35)
```

I believe this is due to the same issue that the projectConfig passed to `isInstalled` at https://github.com/react-native-community/cli/blob/641b21f583c97e3d48ce87d5fe804f42db92fa5c/packages/platform-ios/src/link/isInstalled.ts#L32 is **NOT** the path that was explicitly set by `--project-path`, but rather the one that was wrongly guessed by `projectConfig`. In that path `RNVAppTVOS.xcodeproj` **does** exist, but `RNVAppTVOS.xcodeproj/project.pbxproj` **does not**
