### ISSUE TITLE
Can't find "asyncRequire.js" 

### ISSUE THREAD

**Issue by minhchienwikipedia** [react-native-community/cli#1616]
## Environment

System:
    OS: macOS 12.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Memory: 27.68 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.20.2/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.66.3 => 0.66.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description
I'm trying to run this command to create bundle file for android
```
react-native bundle --entry-file index.js  --platform android --dev false --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res
```
but I'm getting this error
```
error Unable to resolve module /Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro-runtime/src/modules/asyncRequire.js from /Users/minhchien/Documents/Coding/ReactNative/PersonalProject/BeenAlone/beenalone-app/src/translations/index.js: 

None of these files exist:
  * ../../../../../../.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro-runtime/src/modules/asyncRequire.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * ../../../../../../.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro-runtime/src/modules/asyncRequire.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import I18n from 'i18n-js';
  2 | import { I18nManager } from 'react-native';
  3 | import auth from '@react-native-firebase/auth';
  4 | import { findBestAvailableLanguage } from 'react-native-localize';.
Error: Unable to resolve module /Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro-runtime/src/modules/asyncRequire.js from /Users/minhchien/Documents/Coding/ReactNative/PersonalProject/BeenAlone/beenalone-app/src/translations/index.js: 

None of these files exist:
  * ../../../../../../.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro-runtime/src/modules/asyncRequire.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * ../../../../../../.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro-runtime/src/modules/asyncRequire.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> 1 | import I18n from 'i18n-js';
  2 | import { I18nManager } from 'react-native';
  3 | import auth from '@react-native-firebase/auth';
  4 | import { findBestAvailableLanguage } from 'react-native-localize';
    at ModuleResolver.resolveDependency (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async addDependency (/Users/minhchien/.nvm/versions/node/v12.20.2/lib/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
```

**Comment by minhchienwikipedia** [comment]
I resolved it by myself, I just try to switch to another node version!
