### ISSUE TITLE
build failed in RN .69.1 on Linux , not Windows, was ok on 0.68.2

### ISSUE THREAD

**Issue by Productivix** [react-native-community/cli#1646]
## Environment
linux 
jre 11
rn 0.69.1

$ react-native info
react-native : commande introuvable
 
## Description
response to "yarn run android" 
is :

BUILD FAILED in 8s

    at makeError (/myproject/node_modules/execa/index.js:174:9)
    at /myproject/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices /myproject/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction /myproject/node_modules/@react-native-community/cli/build/index.js:192:9)

## Reproducible Demo
main part of package.json : 
```
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.7",
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-masked-view/masked-view": "^0.2.6",
    "@react-navigation/bottom-tabs": "^6.3.2",
    "@react-navigation/core": "^6.2.2",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "axios": "^0.27.2",
    "i18next": "^21.8.13",
    "react": "18.0.0",
    "react-i18next": "^11.18.0",
    "react-native": "0.69.1",
    "react-native-background-fetch": "^4.1.1",
    "react-native-device-info": "^10.0.0",
    "react-native-gesture-handler": "^2.5.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-localize": "^2.2.2",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-vector-icons": "^9.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.70.3",
    "react-test-renderer": "18.0.0"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
and with the same stack , on Windows : no problems, 
in RN 0.68.2 , both platforms : no problems
thank you !

**Comment by Productivix** [comment]
sorry nothing to do here.
