### ISSUE TITLE
[profile-hermes]: no such file or directory, open '/data/user/0/com.sayurbox/cache/sampling-profiler-trace*.cpuprofile/sampling-profiler-trace*-converted.json

### ISSUE THREAD

**Issue by galihlprakoso** [react-native-community/cli#1690]
## Environment

```
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 25.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 3.2.2 - ~/.asdf/shims/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: javac 11 - /Users/[mypath]/.asdf/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

I have successfuly start and stop Hermes Profiling and the toast is showing the path of the *.cpuprofile path. But when I tried to run this command:
`npx react-native profile-hermes /data/user/0/com.mypackage/cache/sampling-profiler-trace8011683141873887643.cpuprofile`

This error was thrown:
```
info Downloading a Hermes Sampling Profiler from your Android device...
info No filename is provided, pulling latest file
info File to be pulled: sampling-profiler-trace4986706971305857154.cpuprofile
error ENOENT: no such file or directory, open '/data/user/0/com.mypackage/cache/sampling-profiler-trace8011683141873887643.cpuprofile/sampling-profiler-trace4986706971305857154-converted.json'.
Error: ENOENT: no such file or directory, open '/data/user/0/com.mypackage/cache/sampling-profiler-trace8011683141873887643.cpuprofile/sampling-profiler-trace4986706971305857154-converted.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at downloadProfile (/Users/[project-path]/node_modules/@react-native-community/cli-hermes/build/profileHermes/downloadProfile.js:163:23)
    at async Object.profileHermes [as func] (/Users/[project-path]/node_modules/@react-native-community/cli-hermes/build/profileHermes/index.js:28:5)
    at async Command.handleAction (/Users/[project-path]/node_modules/@react-native-community/cli/build/index.js:192:9)
```

When I checked it through adb shell, the file is there safe and sound:
```
a50:/data/user/0/com.mypackage/cache $ ls
WebView         dd-web-rum-v2
dd-crash-v2     image_cache
dd-logs-v2      instrument
dd-rum-v2       ndk_crash_reports_v2
dd-tracing-v2   sampling-profiler-trace4986706971305857154.cpuprofile
dd-web-logs-v2  sampling-profiler-trace8011683141873887643.cpuprofile
```

**Comment by galihlprakoso** [comment]
Turns out my command was wrong I'm sorry. 
```
npx react-native profile-hermes /data/user/0/com.mypackage/cache/sampling-profiler-trace8011683141873887643.cpuprofile
```
This should be path directory:
```
/data/user/0/com.mypackage/cache/sampling-profiler-trace8011683141873887643.cpuprofile
```
