### ISSUE TITLE
Initializing from template fails at 'Installing CocoaPods dependencies'

### ISSUE THREAD

**Issue by cjhines** [react-native-community/cli#1838]
## Environment

```
System:
    OS: macOS 12.6.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 295.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 23, 25, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Google APIs Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

The following init command fails on the step 'Installing CocoaPods dependencies'

`npx react-native init MyApp --npm --template https://gitlab.com/cjhines/react-native-template`

Error:

```
error /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/spec_set.rb:86:in `block in materialize': Could not find digest-crc-0.6.4 in any of the sources (Bundler::GemNotFound)
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `map!'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/spec_set.rb:80:in `materialize'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/definition.rb:170:in `specs'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/definition.rb:237:in `specs_for'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/definition.rb:226:in `requested_specs'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/runtime.rb:101:in `block in definition_method'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/runtime.rb:20:in `setup'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler.rb:149:in `setup'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
	from /Users/chris/.rvm/rubies/ruby-2.7.6/lib/ruby/2.7.0/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
    at createFromTemplate (/Users/chris/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:129:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.initialize [as func] (/Users/chris/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/init/init.js:181:3)
    at async Command.handleAction (/Users/chris/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js:106:9)
```

**Comment by adamTrz** [comment]
Hi @cjhines thanks for reporting!
Unfortunately I wasn't able to reproduce the issue, `init` worked fine on my machine which leads to assumption that maybe you have some issues with bundler maybe?
Could you try to install pods manually? 🙏

**Comment by cjhines** [comment]
@adamTrz You were able to `init` with my template or with the default template?

Manually installing for me works, but it's not ideal

**Comment by adamTrz** [comment]
> @adamTrz You were able to `init` with my template or with the default template?
> 
> 
> 
> Manually installing for me works, but it's not ideal since I can't test test template scripts

With your template.
