### ISSUE TITLE
init project crashed on Ubntu 

### ISSUE THREAD

**Issue by techUdayMungalpara** [react-native-community/cli#2156]
## Environment

```
 System:
  OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
  Memory: 3.64 GB / 7.49 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.8.0
    path: /snap/node/7844/bin/node
  Yarn:
    version: 1.22.19
    path: /snap/node/7844/bin/yarn
  npm:
    version: 10.1.0
    path: /snap/node/7844/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10811636
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
npmGlobalPackages:
  "*react-native*": Not Found`
```

#

i triedrto eate react native project using cli using npx react-native@latest init AwesomeProject i try to solve this issue from past 4 days but not able to find solution .
## init project crashed on Ubntu
```✔ Downloading template
⠋ Copying template/home/uday/.npm/_npx/7930a8670f922cdb/node_modules/graceful-fs/polyfills.js:265
        if (!chownErOk(er)) throw er
                            ^

Error: ENOENT: no such file or directory, chmod '/home/uday/Desktop/sd/myProjectNameas/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png'
    at Object.chmodSync (node:fs:1961:3)
    at Object.chmodSync (/home/uday/.npm/_npx/7930a8670f922cdb/node_modules/graceful-fs/polyfills.js:263:21)
    at ReadStream.<anonymous> (/home/uday/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/tools/copyFiles.js:83:19)
    at ReadStream.emit (node:events:514:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/home/uday/Desktop/sd/myProjectNameas/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png'
}

Node.js v20.8.0
```

**Comment by szymonrybczak** [comment]
Hey @techUdayMungalpara, we're aware of this issue. Fix will be released soon.

**Comment by szymonrybczak** [comment]
For now you cannot unfortunately, sorry for trouble! I'll do my best to release this fix as soon as possible 🙌
