### ISSUE TITLE
Error: Cannot find module 'metro-hermes-compiler'

### ISSUE THREAD

**Issue by truong-hua** [react-native-community/cli#2246]
## Environment

```
yarn run react-native info
yarn run v1.22.19
$ /Users/administrator/builds/Tgfi3yuy/0/doopage/doopage_mobile/node_modules/.bin/react-native info
warn Package rn-fetch-blob contains invalid configuration: "dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
info Fetching system and libraries information...
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 312.47 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/yarn--1704647492734-0.8925470205510826/node
    Yarn: 1.22.19 - /var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/yarn--1704647492734-0.8925470205510826/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      Build Tools: 31.0.0
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.8.1 - /opt/homebrew/opt/openjdk@17/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.11 => 0.69.11
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 1.33s.
```

## Description

When I try to build an ipa file with profile Debug, the app can not be started and crash immediately with the error below:

```
Error: Cannot find module 'metro-hermes-compiler'
Require stack:
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/shared/output/bundle.flow.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/shared/output/bundle.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/bundle.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/index.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/build/commands/index.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/build/index.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli/build/commands/index.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli/build/index.js
- /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/react-native/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at getBytecodeVersion (/private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:60:10)
    at Server._parseOptions (/private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:364:7)
    at Server._processRequest (/private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:389:28)
    at processRequest (/private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/Server.js:358:10)
    at /private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/@rnx-kit/metro-config/src/assetPluginForMonorepos.js:71:12
    at call (/private/var/folders/9b/r9bch3bj10x1d4bzly3vmcn80000gn/T/eas-build-local-nodejs/050f5912-d3d0-407c-9074-b5feb498f8c7/build/node_modules/connect/index.js:239:7)
```

This error does not happen and ipa file can work properly if I change the build profile to Release. But my expectation is to provide an ipa file with profile Debug to our internal tester for some verification and in our process, the Debug profile also provide some useful tools to internal team. This one work perfectly with older react native version.

FYI. we do not have hermes enabled, I tried to switch the hermes enabled/disabled and it does not help.

Our react-native-community/cli version is: 
```
├─ react-native@0.69.11
│  ├─ @jest/create-cache-key-function@^27.0.1
│  ├─ @react-native-community/cli-platform-android@^8.0.4
│  ├─ @react-native-community/cli-platform-ios@^8.0.4
│  ├─ @react-native-community/cli@^8.0.4
├─ metro-hermes-compiler@0.70.4
```

## Reproducible Demo

Build a react native project to IPA file with profile Debug

**Comment by szymonrybczak** [comment]
hey @truong-hua, React Native [v0.69](https://reactnative.dev/versions) is no longer supported, please try upgrading your app - it may fix your issue 👍

**Comment by medic345** [comment]
@truong-hua Did you ever find a solution? I'm running React Native v0.73.5 and Im getting the same error.
