### ISSUE TITLE
react native doctor fail on windows 11

### ISSUE THREAD

**Issue by kyborq** [react-native-community/cli#2461]
## React Native Info

```
System:
  OS: Windows 11 10.0.26100
  CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz
  Memory: 9.51 GB / 15.79 GB
Binaries:
  Node:
    version: 20.15.1
    path: D:\Program Files\NodeJS\node.EXE
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: D:\Program Files\NodeJS\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.35027.167 (Visual Studio Community 2022)
Languages:
  Java: 17.0.11
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.3
    wanted: 0.74.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

## Description

```
⠏ Running diagnostics...error Command failed with exit code 1: wmic datafile where name="C:\\Users\\Konstantin\\AppData\\Local\\Android\\android-studio\\bin\\studio.exe" get Version
"wmic" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
Error: Command failed with exit code 1: wmic datafile where name="C:\\Users\\Konstantin\\AppData\\Local\\Android\\android-studio\\bin\\studio.exe" get Version
"wmic" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
    at makeError (D:\Projects\AwesomeProject\node_modules\execa\lib\error.js:60:11)
    at handlePromise (D:\Projects\AwesomeProject\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getDiagnostics (D:\Projects\AwesomeProject\node_modules\@react-native-community\cli-doctor\build\tools\healthchecks\androidStudio.js:42:11)
    at async D:\Projects\AwesomeProject\node_modules\@react-native-community\cli-doctor\build\commands\doctor.js:116:11
    at async Promise.all (index 2)
    at async iterateOverHealthChecks (D:\Projects\AwesomeProject\node_modules\@react-native-community\cli-doctor\build\commands\doctor.js:106:20)
    at async Promise.all (index 1)
    at async Object.doctorCommand [as func] (D:\Projects\AwesomeProject\node_modules\@react-native-community\cli-doctor\build\commands\doctor.js:140:35)
    at async Command.handleAction (D:\Projects\AwesomeProject\node_modules\@react-native-community\cli\build\index.js:116:9)
```

React Native doctor failed event execute a command because I don't have android studio installed in that location (installed in "D:\Program Files\Android\Android Studio\bin\studio64.exe"). But it can build, everything is fine

**Comment by szymonrybczak** [comment]
hey! sometimes custom paths aren't correctly detected by `doctor`, last time I check it was working when installing new Android Studio. If your build is passing anyway you should be good to go!
