### ISSUE TITLE
Cannot build on real device

### ISSUE THREAD

**Issue by JackJBlundell** [react-native-community/cli#2474]
## Environment

System:
  OS: macOS 14.4
  CPU: (8) arm64 Apple M1
  Memory: 180.66 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.08.05.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/jackblundell/.rvm/gems/ruby-2.7.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 22.0.2
    path: /opt/homebrew/opt/openjdk/bin/javac
  Ruby:
    version: 3.3.4
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Description

When I try to run my React Native app on a real iOS device, I am faced with the following error:

```

Showing All Messages
TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined

    at promisify (internal/util.js:279:11)

    at Object.<anonymous> (/Users/jackblundell/Desktop/Testing/2.0/RouteBuddies/node_modules/@react-native-community/cli-clean/build/clean.js:67:39)

```

## Reproducible Demo

With my specifications, just creating an application with npx react-native init AppName --template react-native-template-typescript

**Comment by JackJBlundell** [comment]
Any help here please? We cannot deploy because of this package...

**Comment by szymonrybczak** [comment]
hey @JackJBlundell, did you resolve your issue? For me running bundling command that you've provided works without any issues in new project:
```
❯ npx react-native bundle --entry-file ./index.js --platform ios --bundle-output ios/main.jsbundle --assets-dest ios
                Welcome to Metro v0.80.10
              Fast - Scalable - Integrated


info Writing bundle output to: ios/main.jsbundle
info Done writing bundle output
info Copying 6 asset files
info Done copying assets
```
