### ISSUE TITLE
Invalid version:latest issue on react native

### ISSUE THREAD

**Issue by KRISH826** [react-native-community/cli#2548]
error Invalid Version: latest.
TypeError: Invalid Version: latest
    at new SemVer (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\semver\classes\semver.js:38:13)
    at compare (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\semver\functions\compare.js:3:3)
    at Object.lt (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\semver\functions\lt.js:2:29)
    at createTemplateUri (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\@react-native-community\cli\build\commands\init\version.js:44:47)
    at createProject (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\@react-native-community\cli\build\commands\init\init.js:338:60)
    at Object.initialize [as func] (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\@react-native-community\cli\build\commands\init\init.js:418:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.handleAction (C:\Users\KRISHNENDU\AppData\Local\npm-cache\_npx\2788f5fbd47acb89\node_modules\@react-native-community\cli\build\index.js:124:9)
info Run CLI with --verbose flag for more details.

**Comment by journey-xt** [comment]
You should specify the RN version；
like ：npx @react-native-community/cli@latest init MyApp --version 0.76.0

**Comment by journey-xt** [comment]
Of course, this is a mistake made by CLI

**Comment by fynally** [comment]
npx @react-native-community/cli@11.0.0 init My_app  --version 0.72.6

I tried to create a new project using an old cli but the project has never finished creating. 
It just kept moving
