### ISSUE TITLE
Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by yinhangfeng** [react-native-community/cli#374]
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 26.78 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 22.0.1, 23.0.3, 24.0.3, 25.0.3, 26.0.3, 27.0.3, 28.0.2, 28.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: git+ssh://git@code.timehouse.build:frontend-rn/react-native.git#wind-0.59-stable => 0.59.15 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

```
error Cannot read property 'update' of undefined
debug TypeError: Cannot read property 'update' of undefined
    at new Server (/Users/yinhf/work/wind/wired-app/node_modules/metro/src/Server.js:675:29)
    at buildBundle (/Users/yinhf/work/wind/wired-app/node_modules/@react-native-community/cli/build/commands/bundle/buildBundle.js:91:18)
```

Server.js
```
    if (this._config.resetCache) {
      this._config.cacheStores.forEach(store => store.clear());

      this._config.reporter.update({
        type: "transform_cache_reset"
      });
    }
```

## Reproducible Demo

maybe this pr #371 causes the reporter to be empty

**Comment by thymikee** [comment]
Released 1.9.4 with a revert, thanks for reporting!

**Comment by thymikee** [comment]
cc @fson mind fixing it?

**Comment by KristineTrona** [comment]
I have the same issue. How can I fix it? 

here is my react-native info output:
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 39.57 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.1.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.8.6
      react-native: ^0.59.5 => 0.59.5
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native: 0.59.9
```

My project is experiencing an issue, where the main.jsbundle file is not automatically created. I try to run ``react-native bundle --entry-file='index.js' --platform='ios' --dev=false --bundle-output='ios/YouTalk/main.jsbundle'``which gives me the following error:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'update' of undefined
 at /Users/myUser/MyAppFolder/node_modules/metro/src/node-haste/DependencyGraph.js:149:23
```

If I look into the DependencyGraph.js and console.log the config form the following piece of code I see that config.reporter is undefined. Why is this happening?

```
static load(config) {
   //  console.log(config); --> this shows that config.reporter is undefined
    return _asyncToGenerator(function*() {
      const initializingMetroLogEntry = log(createActionStartEntry('Initializing Metro'));
      config.reporter.update({
        type: 'dep_graph_loading'
      });
  ...
```

**Comment by thymikee** [comment]
@KristineTrona remove `@react-native-community/cli` from the lockfile and regenerate it (reinstall packages). That should fetch the latest version with has a fix.

**Comment by KristineTrona** [comment]
@thymikee Thank you! Indeed, removing the lockfile and reinstalling the packages solved the issue!
