### ISSUE TITLE
Unable to link realm

### ISSUE THREAD

**Issue by chaitanyaevoke** [react-native-community/cli#380]
## Environment

Android and iOS

 React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 8.97 GB / 15.90 GB
    Binaries:
      npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

## Description

Installed realm using "npm install realm". And trying to link realm using the following command
"react-native link realm".  Below is the error.

**error Something went wrong while linking. Error: Expected "/*" but "=" found.
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues
error Expected "/*" but "=" found.. Run CLI with --verbose flag for more details.**

**Comment by thymikee** [comment]
Can you run with the `--verbose` flag for more details where that happens?

**Comment by chaitanyaevoke** [comment]
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
debug Package to link: realm
error Something went wrong while linking. Error: Expected "/*" but "=" found.
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues
error Expected "/*" but "=" found.
debug SyntaxError: Expected "/*" but "=" found.
    at peg$buildStructuredError (D:\react_native\hire_git\v7\Hire\node_modules\xcode\lib\parser\pbxproj.js:429:12)
    at Object.peg$parse [as parse] (D:\react_native\hire_git\v7\Hire\node_modules\xcode\lib\parser\pbxproj.js:1891:11)
    at pbxProject.parseSync (D:\react_native\hire_git\v7\Hire\node_modules\xcode\lib\pbxProject.js:63:24)
    at isInstalled (D:\react_native\hire_git\v7\Hire\node_modules\@react-native-community\cli\build\commands\link\ios\isInstalled.js:38:71)
    at Object.isInstalled (D:\react_native\hire_git\v7\Hire\node_modules\@react-native-community\cli\build\commands\link\ios\common\isInstalled.js:23:35)
    at Object.keys.forEach.platform (D:\react_native\hire_git\v7\Hire\node_modules\@react-native-community\cli\build\commands\link\linkDependency.js:29:36)
    at Array.forEach (<anonymous>)
    at linkDependency (D:\react_native\hire_git\v7\Hire\node_modules\@react-native-community\cli\build\commands\link\linkDependency.js:18:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)

**Comment by thymikee** [comment]
Looks like it comes from `xcode` so seemingly Realm is doing something unexpected in their `project.pbxproj` or maybe you have some merging issues?

**Comment by chaitanyaevoke** [comment]
Yes, we got merging issues. Any workaround solution to resolve this issue?

**Comment by grabbou** [comment]
The `pbxproj` is invalid and cannot be parsed. We should probably add a better error message for that error.

@chaitanyaevoke, please resolve remaining conflicts (or open the project with XCode) and then, try linking it again.

Also, please consider attaching `.pbxproj` here for debugging purposes. It's a file inside `YourProject.xcodeproj` (open it just like any other folder)
