### ISSUE TITLE
console.log doesn't log in terminal

### ISSUE THREAD

**Issue by svipas** [react-native-community/cli#593]
## Environment

```
System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Memory: 107.71 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.1 - ~/.nvm/versions/node/v10.16.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```
## Description

If I try to access: `http://localhost:8081/log-to-console`, I get this error and I can't see any logs in the terminal

```
Connect
500 SyntaxError: Unexpected end of JSON input
   at JSON.parse (<anonymous>)
   at _default (/Users/svipas/Documents/Retailer-ipad-app/node_modules/@react-native-community/cli/build/commands/server/middleware/logToConsoleMiddleware.js:39:21)
   at call (/Users/svipas/Documents/Retailer-ipad-app/node_modules/connect/index.js:239:7)
   at next (/Users/svipas/Documents/Retailer-ipad-app/node_modules/connect/index.js:183:5)
   at openURLMiddleware (/Users/svipas/Documents/Retailer-ipad-app/node_modules/@react-native-community/cli/build/commands/server/middleware/openURLMiddleware.js:45:5)
   at call (/Users/svipas/Documents/Retailer-ipad-app/node_modules/connect/index.js:239:7)
   at next (/Users/svipas/Documents/Retailer-ipad-app/node_modules/connect/index.js:183:5)
   at /Users/svipas/Documents/Retailer-ipad-app/node_modules/@react-native-community/cli/build/commands/server/middleware/openStackFrameInEditorMiddleware.js:29:7
   at call (/Users/svipas/Documents/Retailer-ipad-app/node_modules/connect/index.js:239:7)
   at next (/Users/svipas/Documents/Retailer-ipad-app/node_modules/connect/index.js:183:5)
```

**Comment by thymikee** [comment]
@cpojer is this known and fixed on RN master?

**Comment by cpojer** [comment]
Accessing this endpoint manually doesn't work, and I would expect it to throw that error.

However, we are changing this to use the websocket connection with Metro so the next RN release will have this feature working without requiring this in the CLI (I still recommend keeping it for now so that it works with 0.60).
