### ISSUE TITLE
A problem occurred evaluating settings ... Text must not be null or empty

### ISSUE THREAD

**Issue by ldco2016** [react-native-community/cli#624]
## Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 114.95 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Description

I have this error in my Jenkins build only:

```
13:18:22 FAILURE: Build failed with an exception.
13:18:22 
13:18:22 * Where:
13:18:22 Script '/Users/nfib/Jenkins/Jenkins-Workspaces/ENGA/ENGAL/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 190
13:18:22 
13:18:22 * What went wrong:
13:18:22 A problem occurred evaluating settings 'NFIBEngage'.
13:18:22 > Text must not be null or empty
```
Others mentioned something about `app/build.gradle`, here is the relevant part of mine:

```
// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

Mention was also made of `android/settings.gradle`, this one is mine:

```
rootProject.name = 'NFIBEngage'
include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
include ':appcenter-crashes'
project(':appcenter-crashes').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-crashes/android')
include ':appcenter-analytics'
project(':appcenter-analytics').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter-analytics/android')
include ':appcenter'
project(':appcenter').projectDir = new File(rootProject.projectDir, '../node_modules/appcenter/android')
include ':react-native-webview'
project(':react-native-webview').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-webview/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

From what I have gathered here:

https://react-native-community.github.io/upgrade-helper/?from=0.53.3&to=0.60.4

The above files are correct.

So what exactly is wrong here and how do I fix it?

In terms of `node_modules/@react-native-community/cli-platform-android/native_modules.gradle` line 190 is this one:

`def json = new JsonSlurper().parseText(reactNativeConfigOutput)`

Could the problem be with how I wrote `index.js` file:

```
/**
 * @format
 */

import { AppRegistry } from "react-native";
// old config code
import KeyboardManager from "react-native-keyboard-manager";
// old config code ^^^
import NFIBEngage from "./App";
import { name as appName } from "./app.json";

// old config code
import { Sentry } from "react-native-sentry";

Sentry.config(
  "https://f33c27ee79b04c1bb5117cac6a97d03c@sentry.io/264268"
).install();

KeyboardManager.setToolbarPreviousNextButtonEnable(true);
// old config code ^^^

AppRegistry.registerComponent("NFIBEngage", () => NFIBEngage);
```

Is `AppRegistry.registerComponent()` written correctly?

## Reproducible Demo

A project that can reproduce the issue is this one:
https://github.com/ldco2016/NFIBEngage

**Comment by ishabo** [comment]
I had the same issue while upgrading from react-native 0.59.5 to 0.60.5. Did you find a solution?

**Comment by ldco2016** [comment]
@ishabo , unfortunately, I am still running into this problem except that now we are not using Jenkins but Azure DevOps, but the error persists.

```
FAILURE: Build failed with an exception.
 
* Where:
Script 'D:\a\1\s\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 191
 
* What went wrong:
A problem occurred evaluating settings 'NFIBEngage'.
> Text must not be null or empty
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 1m 42s
Error: The process 'D:\a\1\s\android\gradlew.bat' failed with exit code 1
 at ExecState._setResult (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.155.0\node_modules\azure-pipelines-task-lib\toolrunner.js:816:25)
 at ExecState.CheckComplete (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.155.0\node_modules\azure-pipelines-task-lib\toolrunner.js:799:18)
 at ChildProcess.<anonymous> (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.155.0\node_modules\azure-pipelines-task-lib\toolrunner.js:721:19)
 at emitTwo (events.js:106:13)
 at ChildProcess.emit (events.js:191:7)
 at maybeClose (internal/child_process.js:886:16)
 at Socket.<anonymous> (internal/child_process.js:342:11)
 at emitOne (events.js:96:13)
 at Socket.emit (events.js:188:7)
```

Currently, now my `app/build.gradle` looks like this:

```
dependencies {
    implementation project(':react-native-device-info')
    implementation project(':react-native-onesignal')
    implementation project(':react-native-immediate-phone-call')
//    implementation project(':RNSwipeView')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.facebook.react:react-native:+"  // From node_modules

    if (enableHermes) {
      def hermesPath = "../../node_modules/hermesvm/android/";
      debugImplementation files(hermesPath + "hermes-debug.aar")
      releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
      implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
```

my `android/settings.gradle` looks like this:

```
rootProject.name = 'NFIBEngage'

include ':react-native-device-info'
project(':react-native-device-info').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-device-info/android')
include ':react-native-onesignal'
project(':react-native-onesignal').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-onesignal/android')
include ':react-native-sentry'
project(':react-native-sentry').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-sentry/android')
include ':react-native-immediate-phone-call'
project(':react-native-immediate-phone-call').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-immediate-phone-call/android')
//include ':RNSwipeView'
//project(':RNSwipeView').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-swipe-view/android')
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
//include ':RNSwipeView'
//project(':RNSwipeView').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-swipe-view/android')

include ':app'
```

This is still the line it complains about:

`def json = new JsonSlurper().parseText(reactNativeConfigOutput)`

**Comment by grabbou** [comment]
Are you all running monorepo / Yarn workspaces? This error happens when project isn't properly configured and `project.android` is null. 

Please attach your configuration (if any) and describe your project structure and where you run the CLI from.

Attached `zip` project would be the best.

**Comment by grabbou** [comment]
This is probably fixed by #768 but I want to make sure with proper reproduction.

**Comment by proof666** [comment]
@grabbou, yes, I use monorepo setup with yarn workspaces. I can’t share my project, but it is simple to reproduce the issue - just setup monorepo folder structure, Init react-native project in /packages/mobile, change all URLs to root node_modules in android .gradle. That’s it.
I will try to create a new project with this setup today.

Currently I fix this issue with patch-package:

diff --git a/node_modules/@react-native-community/cli-platform-android/native_modules.gradle b/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
index 30ddaf1..7412ec2 100644
--- a/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
+++ b/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
@@ -170,7 +170,7 @@ class ReactNativeModules {
 
     def cmdProcess
     def root = getReactNativeProjectRoot()
-    def command = "node ./node_modules/react-native/cli.js config"
+    def command = "node ../../node_modules/react-native/cli.js config"
     def reactNativeConfigOutput = ""
 

I already see #768, and I think it will fix this issue. But I didn’t try to run it.

Ps: sorry for formatting, I’m from mobile

**Comment by sibelius** [comment]
I've solved like this on `native_modules.gradle`

```diff
- def command = "${npx} --quiet --no-install react-native config"
+ def command = "yarn --silent react-native config"
` ``
