### ISSUE TITLE
Not able to link any module with react-native link moduleName.

### ISSUE THREAD

**Issue by tosifkhan01** [react-native-community/cli#731]
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
      Memory: 3.75 GB / 7.88 GB
    Binaries:
      npm: 6.2.0 - C:\Users\Tosif Khan\AppData\Roaming\npm\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5522156

react-native-cli: 2.0.1
react-native: 0.59.0

**Issue**:
When I'm using react-native link moduleName, I'm getting this error below.

react-native link anyModule --verbose

debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...

**error No package found. Are you sure this is a React Native project?
error Cannot read property '_text' of undefined**

debug TypeError: Cannot read property '_text' of undefined
    at SAXParser.parser_text [as ontext] (D:\myHealthyYou\node_modules\xmldoc\lib\xmldoc.js:235:39)
    at emit (D:\myHealthyYou\node_modules\sax\lib\sax.js:639:35)
    at closeText (D:\myHealthyYou\node_modules\sax\lib\sax.js:649:26)
    at emitNode (D:\myHealthyYou\node_modules\sax\lib\sax.js:643:26)
    at SAXParser.write (D:\myHealthyYou\node_modules\sax\lib\sax.js:1195:15)
    at new XmlDocument (D:\myHealthyYou\node_modules\xmldoc\lib\xmldoc.js:199:15)
    at readManifest (D:\myHealthyYou\node_modules\@react-native-community\cli\build\tools\android\readManifest.js:44:10)
    at Object.projectConfig (D:\myHealthyYou\node_modules\@react-native-community\cli\build\tools\android\index.js:66:46)
    at Object.keys.forEach.platform (D:\myHealthyYou\node_modules\@react-native-community\cli\build\commands\link\getProjectConfig.js:25:62)
    at Array.forEach (<anonymous>)

**Comment by thymikee** [comment]
Looks like the XML inside your Android manifest is invalid. We use it to determine the package name.

**Comment by tosifkhan01** [comment]
> Looks like the XML inside your Android manifest is invalid. We use it to determine the package name.

@thymikee Yes, I had commented code in manifest and now when I removed that code it's working fine. Thank You. :)
