### ISSUE TITLE
Error: Failed to get dependency config when try to unlink

### ISSUE THREAD

**Issue by lucianomlima** [react-native-community/cli#828]
## Environment
```sh
info 
  React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 6.22 GB / 16.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.15.3/bin/yarn
      npm: 6.11.2 - ~/.nvm/versions/node/v10.15.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
      Android SDK:
        API Levels: 25, 26, 27, 28, 29
        Build Tools: 25.0.3, 26.0.3, 27.0.3, 28.0.3, 29.0.0, 29.0.2
        System Images: android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description
Same problem of #273 and #498. I'm not using CocoaPods.

```sh
$ yarn react-native unlink react-native-firebase --verbose
yarn run v1.17.3
$ /Users/luciano/projects/app/residencia-app/node_modules/.bin/react-native unlink react-native-firebase --verbose
error Failed to get dependency config
debug Error: Failed to get dependency config
    at getDependencyConfig (/Users/luciano/projects/app/residencia-app/node_modules/@react-native-community/cli/build/commands/link/getDependencyConfig.js:49:11)
    at allDependencies.map.dependency (/Users/luciano/projects/app/residencia-app/node_modules/@react-native-community/cli/build/commands/link/unlink.js:95:125)
    at Array.map (<anonymous>)
    at Object.unlink [as func] (/Users/luciano/projects/app/residencia-app/node_modules/@react-native-community/cli/build/commands/link/unlink.js:95:74)
    at Promise.resolve.then (/Users/luciano/projects/app/residencia-app/node_modules/@react-native-community/cli/build/cliEntry.js:152:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by thymikee** [comment]
We're getting rid of `link` in favor of "autolinking" soon, so there's no incentive from us fixing these issues unfortunately. Thanks for caring to file an issue though, appreciated :)

**Comment by lucianomlima** [comment]
What I can do so? We will upgrade the app soon, but not now and I need to get the cli working. What I can do?

**Comment by thymikee** [comment]
Check out similar issues, like this one: https://github.com/react-native-community/cli/issues/273. If it doesn't help, you'll need to unlink manually (see manual instructions for linking for this library and apply in reverse order).
