### ISSUE TITLE
when I am doing npx react-native start and npx react-native run-android it throws an error.

### ISSUE THREAD

**Issue by SupriyaGo** [react-native-community/cli#881]
## Ask your Question
error- 

/home/supu/Documents/Projects/ProjectUniq/node_modules/@react-native-community/cli/build/cliEntry.js:124
  let output = [_chalk().default.bold(`react-native ${cmdName} ${this.usage()}`), this._description ? `\n${this._description}\n` : '', ...sourceInformation, `${_chalk().default.bold('Options:')}`, this.optionHelp().replace(/^/gm, '  ')];
                                                                                                                                       ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/supu/Documents/Projects/ProjectUniq/node_modules/@react-native-community/cli/build/index.js:5:40)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by thymikee** [comment]
Please upgrade your Node version, seems like you're on something lower than 8.3.
