### ISSUE TITLE
Suggest matching commands if the user makes a typo

### ISSUE THREAD

**Issue by jamesgeorge007** [react-native-community/cli#905]
## Describe the Feature

Suggest matching commands if the user mistypes. For instance, `react-native-cli ini` should show up the help message along with a friendly suggestion such as `Did you mean init?`

## Possible Implementations

We can make use of the [didyoumean.js](https://github.com/dcporter/didyoumean.js/) matching engine.

**Comment by jamesgeorge007** [comment]
I would be happy to shoot a PR on receiving the green signal :raised_hands:

**Comment by thymikee** [comment]
Sure, I love the idea! Please use plain Levenshtein though, like https://github.com/sindresorhus/leven#readme

**Comment by jamesgeorge007** [comment]
@thymikee it seems couple of type definition libraries are missing out. Installing the dependencies results in the following:-

```md
Building..................................................................packages/tools/src/groupFilesByType.ts:9:23 - error TS7016: Could not find a declaration file for module 'lodash'. '/home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/node_modules/lodash/lodash.js' implicitly has an 'any' type.
  Try `npm install @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

9 import {groupBy} from 'lodash';
                        ~~~~~~~~

packages/tools/src/groupFilesByType.ts:10:18 - error TS2307: Cannot find module 'mime'.

10 import mime from 'mime';
                    ~~~~~~

packages/tools/src/groupFilesByType.ts:24:26 - error TS7006: Parameter 'type' implicitly has an 'any' type.

24   return groupBy(assets, type => (mime.getType(type) || '').split('/')[0]);
                            ~~~~

packages/debugger-ui/src/middleware/index.ts:1:25 - error TS2307: Cannot find module 'serve-static'.

1 import serveStatic from 'serve-static';
                          ~~~~~~~~~~~~~~


Found 4 errors.


Unable to build TypeScript definition files
Error: Command failed: node /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/node_modules/typescript/bin/tsc -b /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/packages/cli /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/packages/cli-types /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/packages/debugger-ui /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/packages/platform-android /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/packages/platform-ios /home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/packages/tools
    at makeError (/home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/node_modules/execa/index.js:174:9)
    at Function.module.exports.sync (/home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/node_modules/execa/index.js:338:15)
    at Object.<anonymous> (/home/james-the-hacker/CodeSpace/GitHub-Projects/react-native-cli/scripts/buildTs.js:38:9)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:931:10)
    at internal/main/run_main_module.js:17:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prebuild: `yarn build:ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by grabbou** [comment]
Any update on this? This is really odd. Anyway, I would suggest installing the dependencies once again with `yarn`.

I am going to label this as a "good first task". Would love to see this landing soon!

**Comment by jamesgeorge007** [comment]
It was something regarding my local environment. Got it fixed :+1:
