### ISSUE TITLE
react-native run-android 'gradlew.bat' is not recognized as an internal or external command, 

### ISSUE THREAD

**Issue by superphil0** [react-native-community/cli#920]
## Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 6.14 GB / 15.93 GB
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5900203
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4

react-native --version => 3.0.4
## Description

When running npx react-native run-android I get the following error
error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
'gradlew.bat' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (C:\code\pocketcoach-app\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:95:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)

## Reproducible Demo

i can reproduce this on an empty project
npx react-native init

## Possible error
I did some digging, the distributed runOnAllDevices.js (with npx)

runs this:
 (0, _child_process().execFileSync)(cmd, gradleArgs, {
      stdio: ['inherit', 'inherit', 'pipe']
    });

(on windows this is "gradlew.bat app:installDebug -PreactNativeDevServerPort=8081")
There is its own section about the difference of execFileSync and exec here:
https://nodejs.org/docs/latest-v10.x/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows

very easy to test in node
child_process.exec("test.bat", function (er, stdout,  stderr){ console.log(stdout)})  
should work

 child_process.execFileSync("test.bat")  
does not

**Comment by superphil0** [comment]
I guess this can be closed, I had my cmd setup to always start in a certain directory, so when it spawns the shell with execFileSync it wasn't in the correct cwd,
