### ISSUE TITLE
doctor command fails with TypeError with missing Android SDK

### ISSUE THREAD

**Issue by kellycampbell** [react-native-community/cli#931]
## Environment

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 369.99 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Description

One of our developers who primarily works on ios gets the following stack trace when running `react-native doctor`:

```
npx react-native doctor
⠇ Running diagnostics...error Cannot read property '0' of undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot read property '0' of undefined

    at Object.getDiagnostics (/Users/.../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/androidSDK.js:73:70)
    at /Users/.../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:109:29
    at Array.map (<anonymous>)
    at iterateOverHealthChecks (/Users/.../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:100:51)
    at Array.map (<anonymous>)
    at iterateOverCategories (/Users/.../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:131:70)
    at Object._default [as func] (/Users/.../node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:133:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Command.handleAction (/Users/.../node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:164:9)
```

I had him add a console.log of the sdks variable:

```
sdks =  { 'Android NDK': '20.0.5594570' }
```

This is with v3.0.4.

**Comment by thymikee** [comment]
I believe this is fixed now. 
Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version.
