### ISSUE TITLE
Cannot find module './xcode'

### ISSUE THREAD

**Issue by kyleglacier** [react-native-community/cli#948]
## Environment

```internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module './xcode'
Require stack:
- /Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js
- /Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js
- /Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/index.js
- /Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js
- /Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js
- /Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/cli.js
- /Users/user/.config/yarn/global/node_modules/react-native-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js:20:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/index.js',
    '/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js',
    '/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/doctor/index.js',
    '/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/commands/index.js',
    '/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js',
    '/Users/user/Desktop/project/Code/project-mobile-app/node_modules/react-native/cli.js',
    '/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js'
  ]
}
```

## Description

Cannot load ./xcode dependency. The file is missing from the node_modules directory.

## Reproducible Demo

```
npx react-native init AwesomeProject --version 0.61.5
```

**Comment by thymikee** [comment]
Sounds like npx issue. Can you try upgrading it (e.g. by bumping Node version)?

**Comment by kyleglacier** [comment]
It's also happening with another project where I've cleared the `node_modules` and reinstalled using only `yarn`. I don't mind to try another npx version currently I'm attempting with 6.13.4, what would you like me to try with?

Thanks!

**Comment by thymikee** [comment]
Look at this line: `/Users/user/.config/yarn/global/node_modules/react-native-cli/index.js`. Please remove the global `react-native-cli`, that should help. It's not necessary anymore.

**Comment by kyleglacier** [comment]
That fixed it, thank-you for your help!

**Comment by kyleglacier** [comment]
Did a bit more testing afterwards. It seems `yarn` is still struggling, but `npm install` resolved the issue in my current project. I just wanted to note that for any future Google searchers.
