### ISSUE TITLE
Command not found: init

### ISSUE THREAD

**Issue by lucianomlima** [react-native-community/cli#964]
## Environment

From another project:
```
  React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 89.82 MB / 8.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
      Yarn: 1.21.1 - ~/.nvm/versions/node/v10.18.0/bin/yarn
      npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.2, 29.0.3
        System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3/11C29 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.6 => 16.8.6
      react-native: 0.59.10 => 0.59.10
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

## Description

Cannot start a new react-native project

## Reproducible Demo

```
$ npx react-native init example
This will walk you through creating a new React Native project in /Users/luciano/projetos/repos/example
Using yarn v1.21.1
Installing react-native...
yarn add v1.21.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "react-native" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
{ Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at run (/Users/luciano/.nvm/versions/node/v10.18.0/lib/node_modules/react-native-cli/index.js:294:5)
    at createProject (/Users/luciano/.nvm/versions/node/v10.18.0/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/Users/luciano/.nvm/versions/node/v10.18.0/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/Users/luciano/.nvm/versions/node/v10.18.0/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 88918,
  stdout: null,
  stderr: null }
Command `yarn add react-native --exact` failed.
```

```
$ npx --ignoreExisting react-native init example
npx: instalou 2 em 1.992s
comando não existe: init
```

**Comment by thymikee** [comment]
Sounds like issue with npm registry that Yarn links to. We don't control it.

**Comment by lucianomlima** [comment]
Ok, I succesfully install `@react-native-community/cli` with npm, but when I try to init a new project fails again during default template download.
I removed yarn from my PC and not working too.

```sh
 luciano@LucianoLima  ~/projects/repos 
$ yarn
zsh: command not found: yarn

 luciano@LucianoLima  ~/projects/repos 
$ npm ls -g --depth=0
/Users/luciano/.nvm/versions/node/v10.18.0/lib
├── appcenter-cli@2.3.3
├── ios-sim@8.0.2
├── lerna@3.20.2
├── npm@6.13.4
└── react-native-cli@2.0.1

npm ERR! peer dep missing: webpack@4.x.x, required by webpack-cli@3.3.10

 luciano@LucianoLima  ~/projects/repos 
$ npx --ignoreExisting react-native init example
npx: instalou 2 em 1.674s
comando não existe: init
```

What else I can try?

**Comment by lucianomlima** [comment]
Try to create a new project with legacy react-native-cli () global installed with npm (with no yarn version installed) and can't make to work too...

```sh
$ react-native init example
This will walk you through creating a new React Native project in /Users/luciano/projetos/repos/example
Installing react-native...
Consider installing yarn to make this faster: https://yarnpkg.com
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

> fsevents@1.2.11 install /Users/luciano/projetos/repos/example/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> core-js@2.6.11 postinstall /Users/luciano/projetos/repos/example/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN react-native@0.61.5 requires a peer of react@16.9.0 but none is installed. You must install peer dependencies yourself.

+ react-native@0.61.5
added 718 packages from 433 contributors and audited 66242 packages in 114.492s

5 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
info Setting up new React Native app in /Users/luciano/projetos/repos/example
info Adding required dependencies
+ react@16.9.0
added 1 package in 20.541s

5 packages are looking for funding
  run `npm fund` for details

info Adding required dev dependencies
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ @react-native-community/eslint-config@0.0.5
+ @babel/runtime@7.8.4
+ babel-jest@24.9.0
+ jest@24.9.0
+ @babel/core@7.8.4
+ react-test-renderer@16.9.0
+ metro-react-native-babel-preset@0.56.4
+ eslint@6.8.0
added 283 packages from 270 contributors, updated 3 packages and audited 957286 packages in 62.377s

20 packages are looking for funding
  run `npm fund` for details

found 4 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
info Installing required CocoaPods dependencies

[!] Invalid `Podfile` file: [!] /Users/luciano/.nvm/versions/node/v10.18.0/bin/node -e console.log(require('@react-native-community/cli').bin);

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@react-native-community/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at [eval]:1:13
    at Script.runInThisContext (vm.js:122:20)
    at Object.runInThisContext (vm.js:329:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at evalScript (internal/bootstrap/node.js:590:27)
.

 #  from /Users/luciano/projetos/repos/example/ios/Podfile:42
 #  -------------------------------------------
 #
 >    use_native_modules!
 #  end
 #  -------------------------------------------

(node:30156) UnhandledPromiseRejectionWarning: Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./example/ios && pod install".
CocoaPods documentation: https://cocoapods.org/
    at installPods (/Users/luciano/projetos/repos/example/node_modules/react-native/node_modules/@react-native-community/cli/build/tools/installPods.js:207:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I can create a react-native@latest project with legacy cli?!
