### ISSUE TITLE
Cannot read property 'join' of null

### ISSUE THREAD

**Issue by elliotmrodriguez** [react-native-community/cli#977]
## Environment
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 3.31 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.12.0
    react-native: ^0.61.5 => 0.61.5
  npmGlobalPackages:
    create-react-native-module: 0.14.0

## Description
Running doctor via `npx @react-native-community/cli doctor` returns the following exception:

```
error Cannot read property 'join' of null
TypeError: Cannot read property 'join' of null
    at getBuildToolsVersion (/Users/mydir/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/androidSDK.js:56:20)
    at Object.getDiagnostics (/Users/mydir/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/commands/doctor/healthchecks/androidSDK.js:67:29)
    at /Users/emrodriguez/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:130:29
    at Array.map (<anonymous>)
    at iterateOverHealthChecks (/Users/mydir/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:120:51)
    at Array.map (<anonymous>)
    at iterateOverCategories (/Users/mydir/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:153:70)
    at Object._default [as func] (/Users/mydir/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/commands/doctor/doctor.js:155:41)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Command.handleAction (/Users/mydir/.npm/_npx/17358/lib/node_modules/@react-native-community/cli/build/index.js:182:9)
``` 

## Reproducible Demo
I am creating a scaffolded native module project using `create-react-native-module`. That project failed to build in Xcode what looks like an inability to find the path to React (I get `RCTBridgeModule.h not found` errors in Xcode when I attempt to build). 

I intended to use this tool to see if it could help me resolve these issues.

**Comment by thymikee** [comment]
Fixed in v4
